# Pip packages configuration
pip_install_packages:
  - name: docker

# Docker configuration
docker_users:
  - "{{ ansible_user }}"
docker_install_compose: true

# PostgreSQL Connection Details
postgres_host: "{{ vault_postgres_host }}"
postgres_port: "6432" # https://yandex.cloud/ru/docs/managed-postgresql/operations/connect#cloud_1
postgres_user: "{{ vault_postgres_user }}"
postgres_password: "{{ vault_postgres_password }}"
postgres_db: "{{ vault_postgres_db }}"

# Redmine Configuration
redmine_secret_key_base: "{{ vault_redmine_secret_key_base }}"

# Web configuration
container_name: redmine
image_name: redmine:5.1
container_port: 3000
host_port: 80

# Ansible configuration 
ansible_user: rinat
ansible_connection: ssh 
ansible_ssh_private_key_file: ~/.ssh/id_rsa