---
# Datadog Configuration
datadog_site: "datadoghq.eu"
datadog_agent_major_version: "7"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: redmine
        url: "{{ public_url }}"
        tls_verify: yes
datadog_api_key: "{{ datadog_api_key }}"